CleanWebApp/Controllers/WeatherController.cs
using AutoMapper;
using CA.Application.Commands;
using CA.Application.Queries;
using CA.Domain;
using CA.Domain.Helpers;
using CA.WebApp.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CleanWebApp.Controllers
{
    public class WeatherController : Controller
    {
        private readonly ILogger<WeatherController> _logger;
        private readonly IMapper _mapper;
        private readonly IMediator _mediator;

        public WeatherController(ILogger<WeatherController> logger,
                                  IMapper mapper,
                                  IMediator mediator)
        {
            _logger = logger;
            _mapper = mapper;
            _mediator = mediator;
            
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var output = new WeatherViewModel();
            output.Countries = await PopulateCountries();
            output.Cities = new List<dynamic>();
            return View(output);
        }

        private async Task<List<dynamic>> PopulateCountries()
        {
            var countries = await _mediator.Send(new GetCountriesQuery());
            var resultList = new List<dynamic>();
            resultList.Add(new { Text = "Select One", Value = "" });
            foreach (var item in countries)
            {
                resultList.Add(new { Text = item.CountryName, Value = item.Id });
            }
            return resultList;
        }

        private async Task<List<dynamic>> PopulateCities(int countryId)
        {
            var results = await _mediator.Send(new GetCitiesByCountryQuery() { CountryId = countryId });
            var resultList = new List<dynamic>();
            resultList.Add(new { Text = "Select One", Value = "" });
            foreach (var item in results)
            {
                resultList.Add(new { Text = item.CityName, Value = item.Id });
            }
            return resultList;
        }


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Index(WeatherViewModel input)
        {
            input.Countries = await PopulateCountries();
            input.Cities = new List<dynamic>();
            if(input.CountryId !=0)
            {
                input.Cities = await PopulateCities(input.CountryId);
            }

            if (ModelState.IsValid)
            {
                var output = await _mediator.Send(new GetWeatherQuery() { CityId = input.CityId});

                input.Output = output;
            }
            return View(input);
        }

    }
}

CleanWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - WebApp</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Head", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Index">Weather</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Country</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                    </li> }
                                else
                                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                    </li>}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div id="overlay">
            <div class="cv-spinner">
                <span class="spinner"></span>
            </div>
        </div>
        <main role="main" class="pb-3">

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CleanWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/index.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>